export const CACHE_KEY = {
  TAX: {
    GET_ALL: "TAX_GET_ALL",
    GET_BY_ID: "TAX_GET_BY_ID"
  },
  ROLE: {
    GET_ALL: "ROLE_GET_ALL",
    GET_BY_ID: "ROLE_GET_BY_ID"
  },
  STAFF: {
    GET_ALL: "STAFF_GET_ALL",
    GET_BY_ID: "STAFF_GET_BY_ID"
  },
  CUSTOMER: {
    GET_ALL: "CUSTOMER_GET_ALL",
    GET_BY_ID: "CUSTOMER_GET_BY_ID"
  },
  DAY_OFF: {
    GET_ALL: "DAY_OFF_GET_ALL",
    GET_BY_ID: "DAY_OFF_GET_BY_ID"
  },
  REVIEW: {
    GET_ALL: "REVIEW_GET_ALL",
    GET_BY_ID: "REVIEW_GET_BY_ID"
  },
  AUTH: {
    GET_ME: "AUTH_GET_ME"
  },
  CATEGORY: {
    GET_ALL: "CATEGORY_GET_ALL",
    GET_BY_ID: "CATEGORY_GET_BY_ID"
  },
  SHIPPING: {
    GET_ALL: "SHIPPING_GET_ALL",
    GET_BY_ID: "SHIPPING"
  },
  PAYMENT_METHOD: {
    GET_ALL: "PAYMENT_METHOD_GET_ALL",
    GET_BY_ID: "PAYMENT_METHOD_GET_BY_ID"
  },
  BRAND: {
    GET_ALL: "BRAND_GET_ALL",
    GET_BY_ID: "BRAND_GET_BY_ID"
  },
  FAQ: {
    GET_ALL: "FAQ_GET_ALL",
    GET_BY_ID: "FAQ_GET_BY_ID"
  },
  TERM: {
    GET_ALL: "TERM_GET_ALL",
    GET_BY_ID: "TERM_GET_BY_ID"
  },
  COUPON: {
    GET_ALL: "COUPON_GET_ALL",
    GET_BY_ID: "COUPON_GET_BY_ID"
  },
  PRODUCT: {
    GET_ALL: "PRODUCT_GET_ALL",
    GET_BY_ID: "PRODUCT_GET_BY_ID",
    GET_PUBLISHED: "PRODUCT_GET_PUBLISHED",
    GET_DRAFT: "PRODUCT_GET_DRAFT",
    GET_POPULAR: "PRODUCT_GET_POPULAR",
    GET_DISCOUNT: "PRODUCT_GET_DISCOUNT",
    GET_BEST_SELLER: "PRODUCT_GET_BEST_SELLER",
    GET_FEATURED: "PRODUCT_GET_FEATURED"
  },
  QUESTION: {
    GET_ALL: "QUESTION_GET_ALL"
  },
  ORDER: {
    GET_ALL: "ORDER_GET_ALL",
    GET_BY_ID: "ORDER_GET_BY_ID"
  }
}
