export const ENV_CONFIG = {
  BASE_API_URL: process.env.NEXT_PUBLIC_BASE_API_URL,
  BASE_SOCKET_URL: process.env.NEXT_PUBLIC_BASE_SOCKET_URL,
  CLOUDINARY_UPLOAD_PRESET: process.env.CLOUDINARY_UPLOAD_PRESET,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_URL: process.env.CLOUDINARY_URL,
  CLOUDINARY_TIMESTAMP: process.env.CLOUDINARY_TIMESTAMP,
  CLOUDINARY_ROOT_FOLDER: process.env.CLOUDINARY_ROOT_FOLDER,
  NEXT_PUBLIC_CUSTOMER_URL: process.env.NEXT_PUBLIC_CUSTOMER_URL
}
