export enum EResourcePermissions {
  REVIEW = "REVIEW",
  FAVORITE = "FAVORITE",
  PRODUCT = "PRODUCT",
  COUPON = "COUPON",
  ADDRESS = "ADDRESS",
  VARIANT = "VARIANT",
  CATEGORY = "CATEGORY",
  ASSET = "ASSET",
  MESSAGE = "MESSAGE"
}
